AWSTemplateFormatVersion: 2010-09-09

Description: Role to enable EKS build

Parameters: 
  Purpose:
    Description: Purpose used in naming the role
    Type: String

Resources:
  EKSRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - eks.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
      RoleName: !Sub eks-${Purpose}-builder
